<?php

namespace projetBundle\Repository;

/**
 * ArretcaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArretcaisseRepository extends \Doctrine\ORM\EntityRepository
{
}
