<?php

namespace projetBundle\Repository;

/**
 * RecuTypeUniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecuTypeUniteRepository extends \Doctrine\ORM\EntityRepository
{
}
