<?php

namespace projetBundle\Repository;

/**
 * RecuStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecuStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
