<?php

namespace projetBundle\Repository;

/**
 * recuTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecuTypeRepository extends \Doctrine\ORM\EntityRepository
{



}
