<?php

namespace projetBundle\Repository;

/**
 * RecuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecuRepository extends \Doctrine\ORM\EntityRepository
{
   /*
    public function getRecuD() {
         
        return $this->createQueryBuilder('r')
            ->select('r.name as nom')
            ->andWhere('r.encaissement = :D')
            ->getQuery()
            ->getResult()
            ;
    }*/

}
