<?php

namespace projetBundle\Repository;

/**
 * TypetransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypetransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
