projet:
    resource: "@projetBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: '@projetBundle/Controller/'
    type: annotation

api:
    resource: '@projetBundle/Controller/'
    type: annotation

