projet:
    resource: "@projetBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: '@projetBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
api:
    resource: '@projetBundle/Controller/'
    type: annotation



api_login_check:
    path: /api/login_check

