<?php

namespace projetBundle\Repository\Entity;

/**
 * TypeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeUserRepository extends \Doctrine\ORM\EntityRepository
{
}
