projet_homepage:
    path:     /
    defaults: { _controller: projetBundle:Default:index }

index:
    path:     /
    defaults: { _controller: projetBundle:post:index }

index:
    path:     /
    defaults: { _controller: projetBundle:Post:index }


caisse_index:
    path:     /caisse
    defaults: { _controller: projetBundle:Caisse:getCaisses }
    
caisse_index1:
    path:     /caisse/{caisse_id}
    defaults: { _controller: projetBundle:Caisse:getCaissebyid}

caisse_index2:
    path:     /caisse
    defaults: { _controller: projetBundle:Caisse:createcaisse}
    